name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
        python: [3.8, "3.10"]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - name: Install dependencies
        run: |
          pip install -q --upgrade pip
          pip install -q cython
          pip install -q numpy
          pip install -q git+https://github.com/doctorado-ml/mdlp
          pip install -q -r requirements/dev.txt
          pip install -q --upgrade codecov coverage black flake8 codacy-coverage
      - name: Lint
        run: |
          black --check --diff mufs
          flake8 --count mufs
      - name: Tests & coverage
        run: |
          coverage run -m unittest -v mufs.tests
          coverage report -m --fail-under=100
